name: scr_vendor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.0.1
  amplify_api: ^1.6.0
  amplify_auth_cognito: ^1.6.0
  amplify_flutter: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - asset/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: asset/fonts/Roboto-Black.ttf
          weight: 900
        - asset: asset/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: asset/fonts/Roboto-Light.ttf
          weight: 300
        - asset: asset/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: asset/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: asset/fonts/Roboto-Thin.ttf
          weight: 100
